/**
 * Worker bindings and per-request context.
 *
 * Kept hand-written rather than generated by `wrangler types` so the comments explaining what
 * each binding is *for* survive. `pnpm cf-typegen` still works; treat its output as a check
 * against this file, not a replacement for it.
 */

import type { ApiTier, KeyTier, PrincipalKind } from './enums.js';

/**
 * The Workers rate-limiting binding.
 *
 * Declared locally instead of importing `RateLimit` from @cloudflare/workers-types: the shape
 * has moved between type-package majors and this Worker only ever calls one method. A local
 * two-line interface cannot break on a types bump.
 */
export interface RateLimitBinding {
  limit(options: { key: string }): Promise<{ success: boolean }>;
}

export interface Env {
  DB: D1Database;
  /** Rendered part/section HTML written by the sync pipeline, plus the permanent diff memos. */
  CONTENT: R2Bucket;

  // One namespace per tier — a namespace carries exactly one limit. See wrangler.jsonc.
  BURST_ANON: RateLimitBinding;
  BURST_REGISTERED: RateLimitBinding;
  BURST_ELEVATED: RateLimitBinding;

  ENVIRONMENT: string;
  SITE_ORIGIN: string;
  PUBLIC_CONTENT_BASE_URL: string;
  ECFR_USER_AGENT: string;
  DOCS_URL: string;

  /**
   * Secret, REQUIRED. Salts the anonymous-quota key so a stored hash cannot be brute-forced
   * back to an IP address from a database dump — the search space of IPv4 is small enough that
   * an unsalted SHA-256 of an address is not a pseudonym, it is an address.
   *
   * Not optional and with no default: a deployment without it cannot meter anonymous traffic
   * honestly, so `requireAnonSalt` (src/auth/quota.ts) fails the request loudly rather than
   * falling back to a constant anyone can read in this repository. Typed as required so the
   * omission is a type error wherever an `Env` is constructed; the runtime check is what
   * catches a missing `wrangler secret put`.
   */
  ANON_SALT: string;
  /** Secret. Bearer token for the operator-only tier-grant endpoint. */
  ADMIN_TOKEN?: string;
}

/** Who is making this request, after key lookup. */
export type Principal =
  | {
      kind: typeof PrincipalKind.Anonymous;
      /** Written as the enum member, not a repeated literal: it IS `ApiTier.Anonymous`. */
      tier: typeof ApiTier.Anonymous;
      /** sha256(salt + client IP + day). The raw IP is never stored or logged. */
      quotaKey: string;
    }
  | {
      kind: typeof PrincipalKind.Key;
      tier: KeyTier;
      keyId: string;
      accountId: string;
      quotaKey: string;
      lastUsedAt: string | null;
    };

export interface QuotaState {
  tier: ApiTier;
  limit: number;
  remaining: number;
  /** Unix seconds at the next UTC midnight, when the daily counter rolls over. */
  reset: number;
}

export interface Variables {
  requestId: string;
  principal: Principal;
  quota: QuotaState;
}

export type AppEnv = { Bindings: Env; Variables: Variables };
